language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9,<1.10'
  - DJANGO='--pre django'
matrix:
  allow_failures:
    - env: DJANGO='--pre django'
  fast_finish: true
install:
  - psql -c 'CREATE DATABASE "django-cursor-pagination"' -U postgres;
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .
script: "./runtests.py"
notifications:
  email: false
